/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni */

#ifndef _Included_com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni
#define _Included_com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni_sendMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni
 * Method:    sendListOfMessages
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni_sendListOfMessages
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_tieto_incubator2017_notificationapp_boardcontroller_ScreenControllerJni_clearScreen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
